#!/usr/bin/env python3
"""
PDF Slicing Tool for Marp Generated Slides

This script extracts specific sections from PDF slides generated by Marp
based on section titles (e.g., "2025年09月15日").

Author: 张江杰
Date: 2025年09月15日
"""

import io
import re
from io import BytesIO
from pathlib import Path
from typing import List, Optional, Tuple

import fitz  # PyMuPDF
import typer
from PIL import Image
from pptx import Presentation
from pptx.util import Inches
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

# Initialize Rich console and Typer app
console = Console()
app = typer.Typer(
    name="PDF Slicer",
    help="Extract specific sections from Marp-generated PDF slides",
    rich_markup_mode="rich",
)


class PDFSlicer:
    """PDF分割处理类"""

    def __init__(self, pdf_path: Path):
        """
        初始化PDF分割器

        Args:
            pdf_path: PDF文件路径
        """
        self.pdf_path = pdf_path
        self.doc = None
        self.sections = []

    def __enter__(self):
        """上下文管理器入口"""
        self.doc = fitz.open(self.pdf_path)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """上下文管理器出口"""
        if self.doc:
            self.doc.close()

    def extract_text_from_page(self, page_num: int) -> str:
        """
        从指定页面提取文本

        Args:
            page_num: 页面编号（从0开始）

        Returns:
            页面文本内容
        """
        if not self.doc or page_num >= len(self.doc):
            return ""

        page = self.doc[page_num]
        return page.get_text()

    def find_section_boundaries(self) -> List[Tuple[str, int, int]]:
        """
        查找所有章节边界

        Returns:
            章节信息列表，格式为：[(标题, 起始页, 结束页), ...]
        """
        if not self.doc:
            return []

        sections = []
        current_section = None
        current_start = 0

        # 匹配日期格式的正则表达式
        date_pattern = re.compile(r"(\d{4}年\d{1,2}月\d{1,2}日)")

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            task = progress.add_task("正在分析PDF结构...", total=len(self.doc))

            for page_num in range(len(self.doc)):
                page_text = self.extract_text_from_page(page_num)

                # 查找日期标题
                date_match = date_pattern.search(page_text)
                if date_match:
                    # 如果找到新的章节，先保存前一个章节
                    if current_section:
                        sections.append((current_section, current_start, page_num - 1))

                    current_section = date_match.group(1)
                    current_start = page_num

                progress.update(task, advance=1)

        # 添加最后一个章节，但需要找到实际的结束页
        if current_section and self.doc:
            # 对于最后一个章节，查找下一个有内容的页面作为结束边界
            # 或者至少包含当前页面
            last_end = current_start

            # 从当前章节开始页的下一页开始查找，找到下一个可能的章节边界
            for page_num in range(current_start + 1, len(self.doc)):
                page_text = self.extract_text_from_page(page_num)
                # 如果找到另一个日期标题，则以前一页为结束
                if date_pattern.search(page_text):
                    last_end = page_num - 1
                    break
                # 如果页面几乎没有内容（可能是空页或结束页），可以考虑在此结束
                elif len(page_text.strip()) > 10:  # 有实质内容
                    last_end = page_num

            sections.append((current_section, current_start, last_end))

        self.sections = sections
        return sections

    def extract_section(
        self,
        target_title: str,
        output_path: Path,
        output_format: str = "pdf",
        include_title: bool = True,
    ) -> bool:
        """
        提取指定标题的章节

        Args:
            target_title: 目标章节标题或序号（如 "1", "2", "3"）
            output_path: 输出文件路径
            output_format: 输出格式 ("pdf", "pptx", "both")
            include_title: 是否包含第一页（标题页）

        Returns:
            是否成功提取
        """
        if not self.sections:
            self.find_section_boundaries()

        # 查找匹配的章节
        target_section = None

        # 检查是否为数字序号
        if target_title.isdigit():
            section_index = int(target_title) - 1  # 转换为0索引
            if 0 <= section_index < len(self.sections):
                target_section = self.sections[section_index]
            else:
                console.print(
                    f"[red]序号 '{target_title}' 超出范围，可用序号: 1-{len(self.sections)}[/red]"
                )
                return False
        else:
            # 按标题文本查找
            for title, start_page, end_page in self.sections:
                if target_title in title or title in target_title:
                    target_section = (title, start_page, end_page)
                    break

        if not target_section:
            if target_title.isdigit():
                console.print(f"[red]未找到序号为 '{target_title}' 的章节[/red]")
            else:
                console.print(f"[red]未找到标题包含 '{target_title}' 的章节[/red]")
            return False

        title, start_page, end_page = target_section

        # 确定实际要提取的页面范围
        pages_to_extract = []

        # 如果需要包含标题页且章节不是从第一页开始
        if include_title and start_page > 0:
            pages_to_extract.append(0)  # 添加标题页（第1页）

        # 添加章节的所有页面
        for page_num in range(start_page, end_page + 1):
            pages_to_extract.append(page_num)

        page_count = len(pages_to_extract)

        console.print(f"[green]找到匹配章节:[/green] {title}")
        if include_title and start_page > 0:
            console.print(
                f"[blue]页面范围:[/blue] 1 (标题页) + {start_page + 1} - {end_page + 1} (共 {page_count} 页)"
            )
        else:
            console.print(
                f"[blue]页面范围:[/blue] {start_page + 1} - {end_page + 1} (共 {page_count} 页)"
            )

        # 根据输出格式决定处理方式
        if output_format in ["pdf", "both"]:
            # 创建新的PDF文档
            new_doc = fitz.open()

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console,
            ) as progress:
                task = progress.add_task("正在提取页面...", total=page_count)

                for page_num in pages_to_extract:
                    if self.doc:
                        new_doc.insert_pdf(
                            self.doc, from_page=page_num, to_page=page_num
                        )
                    progress.update(task, advance=1)

            # 保存PDF文档
            pdf_output_path = (
                output_path
                if output_format == "pdf"
                else output_path.with_suffix(".pdf")
            )
            new_doc.save(pdf_output_path)
            new_doc.close()

            console.print(f"[green]✓ PDF已保存到:[/green] {pdf_output_path}")

        # 如果需要转换为PPT
        if output_format in ["pptx", "both"]:
            pptx_path = (
                output_path
                if output_format == "pptx"
                else output_path.with_suffix(".pptx")
            )

            if output_format == "pptx":
                # 只输出PPTX时，直接从原PDF提取指定页面转换
                self.extract_pages_to_pptx_from_list(pages_to_extract, pptx_path)
            else:
                # 同时输出时，从生成的PDF转换
                self.pdf_to_pptx(pdf_output_path, pptx_path)

        return True

    def extract_pages_to_pptx_from_list(
        self, page_list: List[int], pptx_path: Path
    ) -> bool:
        """
        根据页面列表提取并转换为PPTX格式

        Args:
            page_list: 要提取的页面编号列表（从0开始）
            pptx_path: 输出PPTX文件路径

        Returns:
            是否成功转换
        """
        try:
            # 创建新的PowerPoint演示文稿
            prs = Presentation()

            # 设置幻灯片尺寸 (16:9比例)
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)

            page_count = len(page_list)

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console,
            ) as progress:
                task = progress.add_task("正在转换为PPT...", total=page_count)

                for page_num in page_list:
                    if self.doc and page_num < len(self.doc):
                        page = self.doc[page_num]

                        # 设置较高的分辨率，提高图像质量
                        mat = fitz.Matrix(2.0, 2.0)  # 2倍放大，提高清晰度
                        pix = page.get_pixmap(matrix=mat)

                        # 将像素图转换为PIL图像
                        img_data = pix.tobytes("png")
                        img = Image.open(BytesIO(img_data))

                        # 保存临时图像文件
                        temp_img_path = pptx_path.parent / f"temp_slide_{page_num}.png"
                        img.save(temp_img_path)

                        # 添加新幻灯片
                        slide_layout = prs.slide_layouts[6]  # 使用空白布局
                        slide = prs.slides.add_slide(slide_layout)

                        # 计算图片尺寸以适应幻灯片
                        slide_width = prs.slide_width
                        slide_height = prs.slide_height

                        # 添加图片到幻灯片
                        slide.shapes.add_picture(
                            str(temp_img_path),
                            Inches(0),
                            Inches(0),
                            slide_width,
                            slide_height,
                        )

                        # 删除临时图像文件
                        temp_img_path.unlink()

                    progress.update(task, advance=1)

            # 保存PowerPoint文件
            prs.save(str(pptx_path))
            console.print(f"[green]✓ PPT已保存到:[/green] {pptx_path}")
            return True

        except Exception as e:
            console.print(f"[red]转换PPT时出错: {e}[/red]")
            return False

    def extract_pages_to_pptx(
        self, start_page: int, end_page: int, pptx_path: Path
    ) -> bool:
        """
        直接从PDF提取指定页面并转换为PPTX格式

        Args:
            start_page: 起始页面（从0开始）
            end_page: 结束页面（包含）
            pptx_path: 输出PPTX文件路径

        Returns:
            是否成功转换
        """
        try:
            # 创建新的PowerPoint演示文稿
            prs = Presentation()

            # 设置幻灯片尺寸 (16:9比例)
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)

            page_count = end_page - start_page + 1

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console,
            ) as progress:
                task = progress.add_task("正在转换为PPT...", total=page_count)

                for page_num in range(start_page, end_page + 1):
                    if self.doc and page_num < len(self.doc):
                        page = self.doc[page_num]

                        # 设置较高的分辨率，提高图像质量
                        mat = fitz.Matrix(2.0, 2.0)  # 2倍放大，提高清晰度
                        pix = page.get_pixmap(matrix=mat)

                        # 将像素图转换为PIL图像
                        img_data = pix.tobytes("png")
                        img = Image.open(BytesIO(img_data))

                        # 保存临时图像文件
                        temp_img_path = pptx_path.parent / f"temp_slide_{page_num}.png"
                        img.save(temp_img_path)

                        # 添加新幻灯片
                        slide_layout = prs.slide_layouts[6]  # 使用空白布局
                        slide = prs.slides.add_slide(slide_layout)

                        # 计算图片尺寸以适应幻灯片
                        slide_width = prs.slide_width
                        slide_height = prs.slide_height

                        # 添加图片到幻灯片
                        slide.shapes.add_picture(
                            str(temp_img_path),
                            Inches(0),
                            Inches(0),
                            slide_width,
                            slide_height,
                        )

                        # 删除临时图像文件
                        temp_img_path.unlink()

                    progress.update(task, advance=1)

            # 保存PowerPoint文件
            prs.save(str(pptx_path))
            console.print(f"[green]✓ PPT已保存到:[/green] {pptx_path}")
            return True

        except Exception as e:
            console.print(f"[red]转换PPT时出错: {e}[/red]")
            return False

    def pdf_to_pptx(self, pdf_path: Path, pptx_path: Path) -> bool:
        """
        将PDF转换为PPTX格式

        Args:
            pdf_path: 输入PDF文件路径
            pptx_path: 输出PPTX文件路径

        Returns:
            是否成功转换
        """
        try:
            # 打开PDF文档
            pdf_doc = fitz.open(pdf_path)

            # 创建新的PowerPoint演示文稿
            prs = Presentation()

            # 设置幻灯片尺寸 (16:9比例)
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console,
            ) as progress:
                task = progress.add_task("正在转换为PPT...", total=len(pdf_doc))

                for page_num in range(len(pdf_doc)):
                    page = pdf_doc[page_num]

                    # 将PDF页面转换为图像
                    mat = fitz.Matrix(2, 2)  # 放大2倍以提高质量
                    pix = page.get_pixmap(matrix=mat)
                    img_data = pix.tobytes("png")

                    # 创建新幻灯片
                    slide_layout = prs.slide_layouts[6]  # 空白布局
                    slide = prs.slides.add_slide(slide_layout)

                    # 将图像添加到幻灯片
                    with io.BytesIO(img_data) as img_stream:
                        # 计算图像在幻灯片中的位置和大小
                        left = Inches(0)
                        top = Inches(0)
                        width = prs.slide_width
                        height = prs.slide_height

                        slide.shapes.add_picture(img_stream, left, top, width, height)

                    progress.update(task, advance=1)

            # 保存PPTX文件
            prs.save(str(pptx_path))
            pdf_doc.close()

            console.print(f"[green]✓ PPT已保存到:[/green] {pptx_path}")
            return True

        except Exception as e:
            console.print(f"[red]转换PPT时出错: {e}[/red]")
            return False

    def list_sections(self) -> None:
        """列出所有可用的章节"""
        if not self.sections:
            self.find_section_boundaries()

        if not self.sections:
            console.print("[yellow]未找到任何章节[/yellow]")
            return

        table = Table(title="可用章节列表")
        table.add_column("序号", style="cyan", no_wrap=True)
        table.add_column("标题", style="magenta")
        table.add_column("页面范围", style="green")
        table.add_column("页数", style="blue")

        for i, (title, start_page, end_page) in enumerate(self.sections, 1):
            page_range = f"{start_page + 1} - {end_page + 1}"
            page_count = str(end_page - start_page + 1)
            table.add_row(str(i), title, page_range, page_count)

        console.print(table)


def validate_pdf_path(pdf_path: str) -> Path:
    """
    验证PDF文件路径

    Args:
        pdf_path: PDF文件路径字符串

    Returns:
        验证后的Path对象

    Raises:
        typer.BadParameter: 文件不存在或不是PDF文件
    """
    path = Path(pdf_path)

    if not path.exists():
        raise typer.BadParameter(f"文件不存在: {pdf_path}")

    if not path.is_file():
        raise typer.BadParameter(f"不是文件: {pdf_path}")

    if path.suffix.lower() != ".pdf":
        raise typer.BadParameter(f"不是PDF文件: {pdf_path}")

    return path


@app.command()
def extract(
    pdf_path: str = typer.Argument(..., help="输入PDF文件路径"),
    title: str = typer.Argument(
        ..., help="要提取的章节标题或序号（如：2025年09月15日 或 1、2、3）"
    ),
    output: Optional[str] = typer.Option(
        None, "--output", "-o", help="输出文件路径（默认为原文件名_标题.pdf）"
    ),
    to_pptx: bool = typer.Option(
        False, "--pptx", help="输出为PowerPoint格式（而非PDF格式）"
    ),
    no_title: bool = typer.Option(
        False, "--no-title", help="不包含第一页（标题页），默认包含"
    ),
):
    """
    根据标题或序号提取PDF章节

    [bold green]示例:[/bold green]

    [cyan]# 使用标题提取（包含标题页）[/cyan]
    [cyan]python split_pdf.py extract presentation.pdf "2025年09月15日"[/cyan]

    [cyan]# 使用序号提取（需先运行 list-sections 查看序号）[/cyan]
    [cyan]python split_pdf.py extract presentation.pdf "1"[/cyan]

    [cyan]# 不包含标题页[/cyan]
    [cyan]python split_pdf.py extract presentation.pdf "1" --no-title[/cyan]

    [cyan]# 指定输出文件[/cyan]
    [cyan]python split_pdf.py extract presentation.pdf "2" --output section.pdf[/cyan]

    [cyan]# 输出为PPT格式[/cyan]
    [cyan]python split_pdf.py extract presentation.pdf "3" --pptx[/cyan]
    """
    # 验证输入文件
    pdf_file = validate_pdf_path(pdf_path)

    # 预先分析PDF以获取章节信息（用于生成合适的文件名）
    actual_title = title
    if title.isdigit():
        # 如果是序号，先获取实际的章节标题用于文件名
        try:
            with PDFSlicer(pdf_file) as temp_slicer:
                temp_slicer.find_section_boundaries()
                section_index = int(title) - 1
                if 0 <= section_index < len(temp_slicer.sections):
                    actual_title = temp_slicer.sections[section_index][0]
        except Exception:
            # 如果获取失败，使用序号作为标题
            actual_title = f"section_{title}"

    # 生成输出文件名
    if not output:
        safe_title = re.sub(r"[^\w\-_.]", "_", actual_title)
        output_file = pdf_file.parent / f"{pdf_file.stem}_{safe_title}.pdf"
    else:
        output_file = Path(output)

    # 确保输出目录存在
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # 显示操作信息
    pptx_info = (
        f"\n[bold blue]转换PPT:[/bold blue] {'是' if to_pptx else '否'}"
        if to_pptx
        else ""
    )
    panel = Panel.fit(
        f"[bold blue]输入文件:[/bold blue] {pdf_file}\n"
        f"[bold blue]目标标题:[/bold blue] {title}\n"
        f"[bold blue]输出文件:[/bold blue] {output_file}{pptx_info}",
        title="PDF分割任务",
        border_style="blue",
    )
    console.print(panel)

    # 执行分割
    try:
        with PDFSlicer(pdf_file) as slicer:
            # 确定输出格式
            if to_pptx:
                output_format = "pptx"
                # 如果用户选择输出PPT，确保输出文件后缀是.pptx
                if output_file.suffix.lower() != ".pptx":
                    output_file = output_file.with_suffix(".pptx")
            else:
                output_format = "pdf"
                # 确保输出文件后缀是.pdf
                if output_file.suffix.lower() != ".pdf":
                    output_file = output_file.with_suffix(".pdf")

            success = slicer.extract_section(
                title,
                output_file,
                output_format=output_format,
                include_title=not no_title,
            )

        if success:
            console.print("\n[bold green]✓ 分割完成！[/bold green]")
        else:
            raise typer.Exit(1)

    except Exception as e:
        console.print(f"[red]错误: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def list_sections(pdf_path: str = typer.Argument(..., help="PDF文件路径")):
    """
    列出PDF中的所有章节

    [bold green]示例:[/bold green]

    [cyan]python slicing_pdf.py list-sections presentation.pdf[/cyan]
    """
    # 验证输入文件
    pdf_file = validate_pdf_path(pdf_path)

    console.print(f"[bold blue]正在分析文件:[/bold blue] {pdf_file}")

    try:
        with PDFSlicer(pdf_file) as slicer:
            slicer.list_sections()

    except Exception as e:
        console.print(f"[red]错误: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def pdf2ppt(
    pdf_path: str = typer.Argument(..., help="输入PDF文件路径"),
    output: Optional[str] = typer.Option(
        None, "--output", "-o", help="输出PPT文件路径（默认为原文件名.pptx）"
    ),
):
    """
    将PDF文件转换为PowerPoint格式

    [bold green]示例:[/bold green]

    [cyan]python slicing_pdf.py pdf2ppt presentation.pdf[/cyan]

    [cyan]python slicing_pdf.py pdf2ppt presentation.pdf --output slides.pptx[/cyan]
    """
    # 验证输入文件
    pdf_file = validate_pdf_path(pdf_path)

    # 生成输出文件名
    if not output:
        output_file = pdf_file.with_suffix(".pptx")
    else:
        output_file = Path(output)

    # 确保输出目录存在
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # 显示操作信息
    panel = Panel.fit(
        f"[bold blue]输入文件:[/bold blue] {pdf_file}\n"
        f"[bold blue]输出文件:[/bold blue] {output_file}",
        title="PDF转PPT任务",
        border_style="blue",
    )
    console.print(panel)

    # 执行转换
    try:
        with PDFSlicer(pdf_file) as slicer:
            success = slicer.pdf_to_pptx(pdf_file, output_file)

        if success:
            console.print("\n[bold green]✓ 转换完成！[/bold green]")
        else:
            raise typer.Exit(1)

    except Exception as e:
        console.print(f"[red]错误: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def info():
    """显示工具信息"""
    info_text = """
[bold blue]PDF Slicing Tool[/bold blue]

这是一个专门为Marp生成的PDF幻灯片设计的分割工具。

[bold green]主要功能:[/bold green]
• 根据日期标题自动识别章节边界
• 提取指定标题或序号的完整章节
• 支持批量查看所有可用章节
• 提供友好的命令行界面
• 支持PDF转PPT格式

[bold green]支持的标题格式:[/bold green]
• 2025年09月15日
• 2024年12月25日
• 等其他日期格式

[bold green]使用方法:[/bold green]
1. 查看所有章节: [cyan]python split_pdf.py list-sections file.pdf[/cyan]
2. 用标题提取章节: [cyan]python split_pdf.py extract file.pdf "2025年09月15日"[/cyan]
3. 用序号提取章节: [cyan]python split_pdf.py extract file.pdf "1"[/cyan]
4. 不含标题页提取: [cyan]python split_pdf.py extract file.pdf "1" --no-title[/cyan]
5. 提取并转换为PPT: [cyan]python split_pdf.py extract file.pdf "1" --pptx[/cyan]
6. 转换整个PDF为PPT: [cyan]python split_pdf.py pdf2ppt file.pdf[/cyan]
"""

    panel = Panel.fit(info_text, title="工具说明", border_style="green")
    console.print(panel)


if __name__ == "__main__":
    app()
